### ISSUE TITLE
Success logging can fail with unicode decode errors

### ISSUE THREAD

**Issue by sbussetti** [nvie/rq#682] opened 2016-03-24 14:04 UTC
Using rq 0.5.6.  I've occasionally run into unicode-decode handler errors when rq attempts to do its success logging.  

```
  File "rq/worker.py", line 431, in work
    self.execute_job(job)
  File "rq/worker.py", line 496, in execute_job
    self.main_work_horse(job)
  File "rq/worker.py", line 533, in main_work_horse
    success = self.perform_job(job)
  File "rq/worker.py", line 604, in perform_job
    log_result = "{0!r}".format(as_text(text_type(rv)))
  File "rq/compat/__init__.py", line 74, in as_text
    return v.decode('utf-8')
  File "encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

Now, while it may be that my response text has a unicode issue in it, I've got no way of handling the exception or verifying if there's a problem with the content of my job response, or even which job caused it because the worker exceptions out on this issue.

That said, my suspicion is not that I have an improperly encoded string, but that my job is returning unicode and falling prey to this issue discussed in: https://wiki.python.org/moin/UnicodeEncodeError

> Paradoxically, a UnicodeEncodeError may happen when _decoding_. The cause of it seems to be the coding-specific decode() functions that normally expect a parameter of type str. It appears that on seeing a unicode parameter, the decode() functions "down-convert" it into str, then decode the result assuming it to be of their own coding. It also appears that the "down-conversion" is performed using the ASCII encoder. Hence an encoding failure inside a decoder.

**Comment by selwin** [comment] 2016-04-07 00:12
Can you make a failing test case for this issue so we can figure out a good way to solve this issue?

**Comment by sbussetti** [comment] 2016-04-07 12:38
Will do!

**Comment by gareth-lloyd** [comment] 2016-05-23 17:39
This error can be reproduced on Python 2.7 by defining a job that returns a string with any non-ASCII byte (i.e. > 127). I actually encountered it because I was returning objects whose `__repr__` functions were returning bytestrings with non-ASCII bytes, and `text_type` in `rq.worker` is python 2.7's unicode literal.

So the logging was effectively calling `unicode(rv)`, which was failing because unicode assumes ASCII if no encoding is specified. 

This case could be fixed by adding an `errors="ignore"` kwarg to the call, but I'm not sure that's the right thing to do. I fixed my problem by fixing my code to obey the (unwritten) rule that the strings returned by repr must only contain ASCII chars.

**Comment by sbussetti** [comment] 2016-05-23 18:57
Thanks for that, I'll put together some failing test cases, sorry for falling off on this one.

**Comment by sbussetti** [comment] 2016-05-23 19:29
e19783d provides failing test case both for my original issue where a valid unicode response fails with a UnicodeEncodeError as well as the issue raised by @gareth-lloyd where a valid bytestring response fails with a UnicodeDecodeError in the same place.

**Comment by selwin** [comment] 2016-05-23 23:42
Thanks for creating the test case. I think wrapping wrapping the object being logged with [as_text()](https://github.com/nvie/rq/blob/master/rq/compat/__init__.py#L54) should fix it. Will try it out when I have more time.

**Comment by gareth-lloyd** [comment] 2016-05-26 11:08
Before logging the representation, this line in Python 2.7  creates a unicode object and then calls `decode` on it in `as_text`. This can still cause errors:

Imagine the job is returning `u"\xe1"`, and try executing the following:

   `unicode(u"\xe1").decode('utf8')`

That's effectively what this line is doing with `as_text(text_type(...))` and it runs smack into the problem @sbussetti linked to above.

**Comment by commandtab** [comment] 2017-02-21 22:23
I'm running into this with rq 0.7.1 under Python 2.7.

**Comment by myme5261314** [comment] 2017-04-14 07:48
Seems this bug has exists for almost a year.

**Comment by selwin** [comment] 2017-04-19 04:17
Fixed in https://github.com/nvie/rq/pull/817

**Closed by selwin** 2017-04-19 04:17 UTC
