### ISSUE TITLE
RQ doesn't support FakeRedis

### ISSUE THREAD

**Issue by jmmills** [nvie/rq#514] opened 2015-04-03 19:45 UTC
RQ doesn't seem to support using FakeRedis to mock redis connection, thus disallowing unit tests sans redis-server.

    E
    ======================================================================
    ERROR: rq_fakeredis.test_rq_with_fakeredis
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/jmills/virtualenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/Users/jmills/rq_fakeredis.py", line 8, in test_rq_with_fakeredis
        queue = Queue(connection=redis)
      File "/Users/jmills/virtualenv/lib/python2.7/site-packages/rq/queue.py", line 58, in __init__
        self.connection = resolve_connection(connection)
      File "/Users/jmills/virtualenv/lib/python2.7/site-packages/rq/connections.py", line 66, in resolve_connection
        return patch_connection(connection)
      File "/Users/jmills/virtualenv/lib/python2.7/site-packages/rq/compat/connections.py", line 23, in patch_connection
        raise ValueError('A StrictRedis or Redis connection is required.')
    ValueError: A StrictRedis or Redis connection is required.
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.001s
    
    FAILED (errors=1)

[rq_fakeredis.py | uploaded via ZenHub](https://files.zenhub.io/551eedd312f7fefa28fc43a7)

**Comment by jonafato** [comment] 2015-05-08 20:28
Duplicate of #282

**Comment by jmmills** [comment] 2015-07-01 18:37
@jonafato yeah, but it was closed and doesn't seem to point to a resolution.

**Comment by jonafato** [comment] 2015-07-01 19:03
It was still open when I made that comment :). It's the more active issue, so if more discussion is to happen, it should probably take place there and possibly reopen the issue if there is a path to a fix.

**Comment by robodude666** [comment] 2015-07-17 16:19
Maybe the official [testing](http://python-rq.org/docs/testing/) simply need to include an example of how to use `mock` with `rq`? There are already a few examples within #282 and googling shows similar solutions; they just need to be documented so people don't think it's a "bug" of `rq`.

**Comment by selwin** [comment] 2015-08-24 05:10
I think we can modify `patch_connection` to this:
```python
def patch_connection(connection):
    # Don't patch already patches objects
    PATCHED_METHODS = ['_setex', '_lrem', '_zadd', '_pipeline', '_ttl']
    if all([hasattr(connection, attr) for attr in PATCHED_METHODS]):
        return connection

    if isinstance(connection, Redis):
        connection._setex = partial(StrictRedis.setex, connection)
        connection._lrem = partial(StrictRedis.lrem, connection)
        connection._zadd = partial(StrictRedis.zadd, connection)
        connection._pipeline = partial(StrictRedis.pipeline, connection)
        connection._ttl = fix_return_type(partial(StrictRedis.ttl, connection))
        if hasattr(connection, 'pttl'):
            connection._pttl = fix_return_type(partial(StrictRedis.pttl, connection))

    else:
        connection._setex = connection.setex
        connection._lrem = connection.lrem
        connection._zadd = connection.zadd
        connection._pipeline = connection.pipeline
        connection._ttl = connection.ttl
        if hasattr(connection, 'pttl'):
            connection._pttl = connection.pttl

    return connection
```
This should allow people to more easily mock Redis. Please let me know if there's any concerns.

**Comment by robodude666** [comment] 2015-08-25 17:05
@selwin :+1:

**Comment by selwin** [comment] 2015-09-22 11:19
Fixed in https://github.com/nvie/rq/commit/0e4112da7a6a18cccbf1069306a6704d407b9b24

**Closed by selwin** 2015-09-22 11:19 UTC
