### ISSUE TITLE
rq worker instances using up lot of memory

### ISSUE THREAD

**Issue by abhisheksachan** [nvie/rq#740] opened 2016-08-11 12:11 UTC
Hello
I have django project which enqueues jobs in a redis queue. What i saw is after is completes its task the rq worker instances are not closed. So its kind of evry time consuming my memory and eventually i run out of memory.

I have a view like this'
    class VideoDetails(APIView):

```
def get(self, request, *args, **kwargs):
    return render(request, "smile_detection/index1.html")

def options(self, request, *args, **kwargs):
    return Response()

def post(self, request, *args, **kwargs):

    print "inside post call------"
    q = Queue(connection=Redis())
    result = q.enqueue(smile_eye_threading.main, request.data.dict())
    return Response(status=HTTP_201_CREATED)
```

Please help me to sort this out.

**Comment by fchevitarese** [comment] 2016-09-05 18:54
I have the very same problem.

**Comment by selwin** [comment] 2017-04-19 05:56
The memory leak could be caused by the jobs you're running through RQ.

As far as I know, RQ itself doesn't cause any leaks. I'm closing this issue for now, but please send a PR if you find any memory leaks in this library.

**Closed by selwin** 2017-04-19 05:56 UTC

**Comment by abhisheksachan** [comment] 2017-04-19 06:00
Yeah, jobs were actually leaking the memory not the RQ, I solved the issue and its working fine now !

**Comment by taewookim** [comment] 2020-08-13 21:41
Having same issue. I have 2 RQ workers + 1 RQ scheduler just idling... i.e. nothing in queue

Just spinning up those is takes the server memory usage from 63 mb (ubuntu 18.04 LTS) to almost 800mb.

Is there some kind of a debug / optimization that can be done?

**Comment by leena-lp** [comment] 2021-05-10 10:46
> Yeah, jobs were actually leaking the memory not the RQ, I solved the issue and its working fine now !

Hi @abhisheksachan ,
  Could you please update here the solution?

**Comment by abhisheksachan** [comment] 2021-05-10 15:49
@leena-lp 
It was my code design which causing the memory leaks, I was using python multiprocessing lib to parallelise my computing, the issue was that every time i was creating a new Process instance globally which were not getting destroyed after the scope was over. So you need to look for these kind of leaks. Good Luck !
