### ISSUE TITLE
uncaught StopRequested during warm shutdown 

### ISSUE THREAD

**Issue by garhiggins** [nvie/rq#585] opened 2015-10-01 18:57 UTC
I saw the following stack trace during a warm shutdown:
Oct 01 17:58:26 cambly app/worker.1:  17:58:26 Warm shut down requested 
Oct 01 17:58:26 cambly app/worker.1:  Process Process-2: 
Oct 01 17:58:26 cambly app/worker.1:  Traceback (most recent call last): 
Oct 01 17:58:26 cambly app/worker.1:    File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap 
Oct 01 17:58:26 cambly app/worker.1:      self.run() 
Oct 01 17:58:26 cambly app/worker.1:    File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 114, in run 
Oct 01 17:58:26 cambly app/worker.1:      self._target(*self._args, **self._kwargs) 
Oct 01 17:58:26 cambly app/worker.1:    File "worker.py", line 94, in work 
Oct 01 17:58:26 cambly app/worker.1:      worker.work() 
Oct 01 17:58:26 cambly app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 421, in work 
Oct 01 17:58:26 cambly app/worker.1:  2015-10-01 17:58:26,465 (31155/MainThread) newrelic.core.agent INFO - New Relic Python Agent (1.13.1.31) 
Oct 01 17:58:26 cambly app/worker.1:      self.execute_job(job) 
Oct 01 17:58:26 cambly app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 484, in execute_job 
Oct 01 17:58:26 cambly app/worker.1:      child_pid = os.fork() 
Oct 01 17:58:26 cambly app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 353, in request_stop 
Oct 01 17:58:26 cambly app/worker.1:      raise StopRequested() 
Oct 01 17:58:26 cambly app/worker.1:  StopRequested 

My understanding of the code is that RQ should be capturing the StopRequested and exiting normally. The trouble is that execute_job has been called (outside of the try/catch StopRequested), but the job state has not been updated to 'busy' yet, so the signal handler throws a StopRequested (when it should probably set _stop_requested), and this StopRequested is uncaught.

Is my understanding correct? Let me know if you need any more details.

**Comment by selwin** [comment] 2015-10-01 23:33
Interesting, I've never seen this before. Can you consistently reproduce this? Also, do you know if the jib has been popped off the queue before this happens?

**Comment by garhiggins** [comment] 2015-10-01 23:51
I've only seen it today, and I think it's pretty inconsistent - my guess is that os.fork() was slow for some reason, which was why I happened to hit it - I had 4 out of 6 threads die with the same trace during a routine restart.

The code, the code that executes after the try/catch (https://github.com/nvie/rq/blob/master/rq/worker.py#L430) but before the worker is updated to 'busy' (https://github.com/nvie/rq/blob/master/rq/worker.py#L502) can 'leak' the StopRequested exception. And os.fork() is probably the only line of code that does anything substantial, which is why all the stack traces I saw were from that line.

Similarly, after the job finishes and the state is updated to 'idle', a StopRequested could again be leaked until the looping code re-enters the try/catch (but, this is probably such a small period of time that it never happens in practice).

**Comment by garhiggins** [comment] 2015-10-01 23:54
I don't fully understand the rationale for StopRequest vs _stop_requested - is the latter so that the job can try to finish execution normally if it's started? It seems like you should toggle this behavior as soon as the job is dequeued then?

**Comment by selwin** [comment] 2015-10-08 11:24
Looks like we can solve the problem by setting state to `busy` before `os.fork()` is called. What do you think?

As for your latter question, this is the current behavior:
1. When CTRL+C is hit for the first time, `worker._stop_requested` is set to `True` to indicate that stop has been requested once. The worker will not quit right away but waits for currently executing job to finish.
2. When CTRL+C is hit for the second time (`worker._stop_requested == True`), the worker will quit right away without waiting for job to finish.

**Comment by garhiggins** [comment] 2015-10-13 18:20
yeah, setting it to busy before the fork would certainly make it far less likely to happen (and, I think it's actually already pretty uncommon) - I think to do it perfectly, there'd need to be some sort of synchronization. I doubt we'll even run into this again and I don't consider this a very critical bug, but I figured I'd report it in case anyone else was more concerned about it.

**Comment by selwin** [comment] 2015-10-14 01:03
Yeah, for now, I'm happy with just moving the state change to before os.fork is called. Mind opening a PR? :)

**Comment by horida** [comment] 2015-10-27 10:52
Like @garhiggins mentioned, in https://github.com/nvie/rq/blob/master/rq/worker.py#L502 the state of the fork is set to busy, the worker itself remains in idle (though in Redis it's registered as busy).

Simply setting the worker to busy before the job execution in https://github.com/nvie/rq/blob/master/rq/worker.py#L431 and back to idle directly after it, solved the problem for me:
```
job, queue = result    
self.set_state('busy') 
self.execute_job(job)  
self.set_state('idle') 
self.heartbeat()       
```

**Comment by selwin** [comment] 2015-10-27 14:32
@horida yup, mind opening a PR?

**Comment by horida** [comment] 2015-10-28 08:44
@selwin done: https://github.com/nvie/rq/pull/594

**Comment by selwin** [comment] 2015-11-08 11:49
Fixed in https://github.com/nvie/rq/pull/594

**Closed by selwin** 2015-11-08 11:49 UTC
