### ISSUE TITLE
Job status not updated when horse dies unexpectedly 

### ISSUE THREAD

**Issue by spiliopoulos** [nvie/rq#702] opened 2016-05-04 20:37 UTC
Hi,

If a workhorse is forcefully terminated (think OOM) then the status of the job is not updated to failed, after the timeout expires. I believe that could be fixed by moving where the timeout is checked from [perform_job](https://github.com/nvie/rq/blob/master/rq/worker.py#L590) (in the work horse which could be terminated) to the [main worker](https://github.com/nvie/rq/blob/master/rq/worker.py#L554). If this is desirable I could create a PR for it.

**Comment by selwin** [comment] 2016-05-04 23:40
Yes, this is something that we need to improve RQ's reliability. In addition to just waiting for the child process to finish, the main worker should periodically (maybe once every 3 seconds?) check that the child process is still alive.

If possible, make it into a dedicated `worker.check_job_progress()` so custom worker classes can extend this if needed.

**Comment by spiliopoulos** [comment] 2016-05-04 23:44
Will do. Hopefully, I will check back in the next days.

**Comment by spiliopoulos** [comment] 2016-05-23 21:13
Finally I had some time to work a bit on this and get some more insight on what happens.

It seems that it's not a matter of monitoring the work horse (any change of state in the work horse is caught  by the main worker's waitpid) but a matter of updating the status of the job in the workhorse which might be killed at any time.

I am considering the following options:

- Leave the workhorse as is but check in the main worker whether the workhorse terminated normally and if not check if the job status has a reasonable value (failed or finished) and if not move it to the failed queue (do you think there might a chance I will be introducing any race conditions?)

- Use a context manager in the workhorse to make sure that the job status is updated even if the workhorse gets killed (with the drawback that we do not handle the case when the workhorse is sent a SIGKILL as in an OOM)

Any advice?

**Comment by selwin** [comment] 2016-05-23 23:29
For me, the best case scenario would be if we go with the first option. There are three things possible outcomes during job execution:

1. Job finishes execution - we can reliably detect this.
2. Job fails by raising an exception during execution - we can reliably detect this.
3. Job fails without raising an exception, this could be caused by segfault, gets terminated by the OS or other reasons. Can we reliably detect this?

**Comment by spiliopoulos** [comment] 2016-05-25 19:37
Pull request #710

**Comment by spiliopoulos** [comment] 2016-09-20 20:04
This should have been closed after #710 was merged.

**Comment by selwin** [comment] 2016-09-21 01:35
Fixed in https://github.com/nvie/rq/pull/710

**Closed by selwin** 2016-09-21 01:35 UTC
